version: '3'

services:
    mongodb:
        image: 'mongo:latest'
        container_name: 'my-mongo-container'
        restart: 'always'
        environment:
            MONGO_INITDB_ROOT_USERNAME: 'admin'
            MONGO_INITDB_ROOT_PASSWORD: 'admin'
            MONGO_INITDB_DATABASE: 'certificate_education'
        ports:
            - '27017:27017'
        volumes:
            - './mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro'

    mongodb2:
        image: 'mongo:latest'
        container_name: 'my-mongo-container-iig'
        restart: 'always'
        environment:
            MONGO_INITDB_ROOT_USERNAME: 'admin'
            MONGO_INITDB_ROOT_PASSWORD: 'admin'
            MONGO_INITDB_DATABASE: 'certificate_education_iig'
        ports:
            - '27018:27017'
        volumes:
            - './mongo-init-iig.js:/docker-entrypoint-initdb.d/mongo-init-iig.js:ro'
